name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install Python
      run: uv python install
    - name: Install dependencies
      run: uv sync
    - name: Run hooks
      run: uv run pre-commit run --all-files
    - name: Run tests
      run: GITHUB_REPOSITORY="" uv run pytest
    - name: Build static version
      run: uv run python freeze.py
      env:
        CNAME: soerface.de
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/

  deploy:
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate sourc
    environment:
      name: github-pages
      url: https://soerface.de

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
